spring.application.name=global_threads_backend
spring.datasource.url=jdbc:mysql://localhost:3306/global_threads_backend
spring.datasource.username=root
spring.datasource.password=Hemu@3433

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080